apiVersion: v1
kind: Service
metadata:
  name: fuzeapibalancer
  labels:
    app: fuzeapi
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    name: http
    targetPort: 5000
  selector:
    app: fuzeapi